name: sfg
channels:
  - javascript
  - conda-forge
  - defaults
dependencies:
- python=3.7
- pip=19.3.1
- numpy=1.17.3
- pandas=0.25.2
- matplotlib=3.1.1
- jupyterlab=1.1.4
- widgetsnbextension=3.5.1
- ipywidgets=7.5.1
- iminuit=1.3.7
- altair=4.0.1
- nodejs=10.13.0
- pip:
    - --editable .

